language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
before_install:
  - sudo add-apt-repository ppa:ultrafredde/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq task
  - task --version
  - pip install taskw
  - pip install mock
  - pip install unittest2
  - pip install megaplan
  - pip install jira.client
install: python setup.py install
script: nosetests -w tests
notifications:
    email: true
    on_success: change
    on_failure: always
