language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install uuid-dev
  - wget http://taskwarrior.org/download/task-2.4.4.tar.gz
  - gunzip task-2.4.4.tar.gz
  - tar xf task-2.4.4.tar
  - cd task-2.4.4
  - cmake .
  - make
  - sudo make install
  - sudo apt-get install -qq pandoc
  - task --version
  - pip install --upgrade pip
  - pip install taskw
  - pip install mock
  - pip install responses
  - pip install PySimpleSOAP
  - cd $TRAVIS_BUILD_DIR
env:
  - JIRAVERSION=1.0.7
  - JIRAVERSION=1.0.10
install:
  - pip install jira==$JIRAVERSION
  - pip install .[jira,megaplan,activecollab,bts,bugzilla,trac,gmail]
  - pip install codecov
  - pip install coverage
script: nosetests -w tests --with-coverage --cover-branches --cover-package=bugwarrior -v
after_success: codecov
notifications:
    email: true
    on_success: change
    on_failure: always
