language: python
python:
 - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install uuid-dev
  - wget http://taskwarrior.org/download/task-2.4.4.tar.gz
  - gunzip task-2.4.4.tar.gz
  - tar xf task-2.4.4.tar
  - cd task-2.4.4
  - cmake .
  - make
  - sudo make install
  - sudo apt-get install -qq pandoc
  - task --version
  - pip install --upgrade pip
  - pip install taskw
  - pip install mock
  - pip install responses
  - pip install PySimpleSOAP
  - cd $TRAVIS_BUILD_DIR
install:
  - pip install .[jira,megaplan,activecollab,bts]
  - pip install coveralls
  - pip install coverage
script: nosetests -w tests --with-coverage --cover-package=bugwarrior
after_success: coveralls
notifications:
    email: true
    irc:
        - "irc.freenode.net#threebean"
    on_success: change
    on_failure: always
