language: python
python:
 - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install uuid-dev
  - wget http://taskwarrior.org/download/task-2.3.0.tar.gz
  - gunzip task-2.3.0.tar.gz
  - tar xf task-2.3.0.tar
  - cd task-2.3.0
  - cmake .
  - make
  - sudo make install
  - sudo apt-get install -qq pandoc
  - task --version
  - pip install taskw
  - pip install mock
  - pip install unittest2
  - cd $TRAVIS_BUILD_DIR
install: python setup.py install
script: nosetests -w tests
notifications:
    email: true
    irc:
        - "irc.freenode.net#threebean"
    on_success: change
    on_failure: always
